"""
Export functionality for reports.
"""

import streamlit as st
import json
from datetime import datetime


def render_export_buttons(results: dict):
    """
    Render export buttons for downloading reports.
    
    Args:
        results: Dictionary containing analysis results
    """
    
    st.subheader("📥 Export Options")
    
    col1, col2, col3 = st.columns(3)
    
    # Export as Markdown
    with col1:
        markdown_content = generate_markdown_report(results)
        st.download_button(
            label="📄 Download Markdown Report",
            data=markdown_content,
            file_name=f"financial_report_{results.get('ticker', 'report')}_{datetime.now().strftime('%Y%m%d')}.md",
            mime="text/markdown",
            use_container_width=True
        )
    
    # Export as JSON
    with col2:
        json_content = json.dumps(results, indent=2)
        st.download_button(
            label="📊 Download JSON Report",
            data=json_content,
            file_name=f"financial_report_{results.get('ticker', 'report')}_{datetime.now().strftime('%Y%m%d')}.json",
            mime="application/json",
            use_container_width=True #width=True
        )
    
    # Export as PDF (optional - requires additional library)
    with col3:
        st.button(
            "📑 Download PDF Report",
            use_container_width=True,
            disabled=True,
            help="PDF export coming soon"
        )


def generate_markdown_report(results: dict) -> str:
    """
    Generate a formatted markdown report from results.
    
    Args:
        results: Dictionary containing analysis results
        
    Returns:
        str: Formatted markdown content
    """
    
    ticker = results.get("ticker", "Unknown")
    timestamp = results.get("timestamp", datetime.now().isoformat())
    
    markdown = f"""# Financial Analysis Report: {ticker}

**Generated:** {timestamp}  
**Investor Perspective:** {results.get('investor_mode', 'Neutral')}

---

## Executive Summary

{results.get('executive_summary', {}).get('key_takeaways', 'No summary available.')}

### Investment Thesis

{results.get('executive_summary', {}).get('investment_thesis', 'No thesis available.')}

---

## Financial Indicators

### Valuation Metrics
- **P/E Ratio:** {results.get('financial_indicators', {}).get('pe_ratio', 'N/A')}
- **PEG Ratio:** {results.get('financial_indicators', {}).get('peg_ratio', 'N/A')}
- **P/B Ratio:** {results.get('financial_indicators', {}).get('pb_ratio', 'N/A')}

### Profitability Metrics
- **ROE:** {results.get('financial_indicators', {}).get('roe', 'N/A')}
- **ROA:** {results.get('financial_indicators', {}).get('roa', 'N/A')}

---

## News & Sentiment

{results.get('news_sentiment', {}).get('summary', 'No news analysis available.')}

---

## Risks & Opportunities

### Key Opportunities
{format_list_items(results.get('risks_opportunities', {}).get('opportunities', []))}

### Key Risks
{format_list_items(results.get('risks_opportunities', {}).get('risks', []))}

---

## Full Analysis

{results.get('full_report', 'Full report not available.')}

---

*This report was generated by FinResearch AI using multi-agent systems.*
"""
    
    return markdown


def format_list_items(items: list) -> str:
    """Format a list of items as markdown bullets."""
    if not items:
        return "- None identified\n"
    
    formatted = ""
    for item in items:
        title = item.get('title', 'Untitled')
        desc = item.get('description', '')
        formatted += f"- **{title}**: {desc}\n"
    
    return formatted